### ISSUE TITLE
DASH validator complains about dependencyId used as per HbbTV spec

### ISSUE THREAD

**Issue by AlaguSundari59** [Dash-Industry-Forum/DASH#30]
Hi team, 

I need to support audio description as per HbbTV spec.

![image](https://user-images.githubusercontent.com/49232798/55470502-60d71d80-5625-11e9-9aff-511c32ad8ed4.png)
 
Below is the code from dash.mpd file.
When i validate this using DASH IF tool, i am getting the error as, 

### **The @dependencyId attribute on the Enhancement Layer Representation shall refer to the Base Layer Representation @id attribute.**
     This error is related to check "" done in dash validator. 

but as part of HbbTV spec, the dependencyId can referred to "Id" (main Audio) from different Adaptation set. Are you missing this check in your validation ???

```
<AdaptationSet>		
	<Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
<Representation audioSamplingRate="48000"  bandwidth="192000" id="Audio-1-deu">
</AdaptationSet>
<AdaptationSet>	
			
<Accessibility
				schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007"
				value="1"/>
<Role
				schemeIdUri="urn:mpeg:dash:role:2011"
				value="commentary"/>
<Representation
				audioSamplingRate="48000"
				bandwidth="192000"
				dependencyId="Audio-1-deu"
				id="Audio-2-deu"
				mediaStreamStructureId="Audio-1-deu">
```

**Comment by akilan27** [comment]
Hi,

Is there a movement on this bug? Thanks.

**Comment by wschidol** [comment]
We have a [pull request open](https://github.com/Dash-Industry-Forum/DASH/pull/29) that fixes this and a few other issues. Feel free to +1 this :-)

**Comment by eceozturk** [comment]
Hi @AlaguSundari59 and @akilan27 ,
The related PR fixing this issue #29 (as @wschidol stated) is now merged. Closing this issue now.

If you still observe any issue, please feel free to reopen this issue and report here.
